### ISSUE TITLE
Fields not hardcoded

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vision-app#2]
Fetch fields from mp-field-visualisation.

NOT as is currently : https://vision.artresearch.net/resource/:MatchingCanditateFields

**Comment by mafragias** [comment]
Required Fields are uploaded to the platform.

**Comment by sophisid** [comment]
This issue won't fix #2 , the fields are returning the values correct but the styling is much worse than before and cannot be implemented as good as before because of the fact that in this case we cannot use a table. Also the timing is as same as before, or it does not have as much difference, and do not cause such problem  as in the UI.  That is why we chosen to implement it was before, so the values can align better in the visualization
