### ISSUE TITLE
Versos of photos

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#39]
Should the matching include also images of the versos of the photos?

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F4358586229865477952597292

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fmarburg%2Fsource%2FMarburg&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F9782892751985544932

**Comment by lklic** [comment]
no, these should not even be indexed in pastec...

**Comment by mafragias** [comment]
hi @lklic , If I remember correctly, you wanted to have them indexed so that you can crop out a part of the photo and to find all the images based on the tag they had. Also Frick doesn't have a way to distinguish between versos and rectos, that I am aware of.

![image](https://user-images.githubusercontent.com/23557768/145961168-1575739f-0a58-49ca-a87c-96fc5f0c6b0f.png)

However I find it weird that they even poped up, because we filter them based on type. We will investigate the issue and let u know.

**Comment by lklic** [comment]
yes, but this is a completely separate project and will require a separate index. It doesn't make sense to have the verso and recto of a photo together in the same index....

Can you clear pastec of all the versos?

**Comment by mafragias** [comment]
Clear versos :
- [x] clear similarity graphs from vision instance
- [x] clear indexes from pastec

**Comment by spykoulouris** [comment]
Has this been fixed? 
I still see some of the Frick's versos

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2FFrick&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F4473850032840880762850662445

**Comment by mafragias** [comment]
@spykoulouris , yes this has been fixed in the case of I Tatti, where type for versos exists, in Frick there is no distinctive type, so that we could ensure which photo is what type, so that we can remove it.
